const kanjiList = [
    // Add Kanji data for Level 1 here
    {
        kanji: "一",
        onyomi: "イチ、イツ",
        kunyomi: "ひと・つ",
        example: "一人 (ひとり)",
        english: "One person",
        nepali: "एक व्यक्ति",
      },
      {
        kanji: "二",
        onyomi: "ニ",
        kunyomi: "ふた・つ",
        example: "二日 (ふつか)",
        english: "Two days",
        nepali: "दुई दिन",
      },
      {
        kanji: "三",
        onyomi: "サン",
        kunyomi: "みっ・つ",
        example: "三日 (みっか)",
        english: "Three days",
        nepali: "तीन दिन",
      },
      {
        kanji: "四",
        onyomi: "シ",
        kunyomi: "よん、よっ・つ",
        example: "四時 (よじ)",
        english: "Four o'clock",
        nepali: "चार बजे",
      },
      {
        kanji: "五",
        onyomi: "ゴ",
        kunyomi: "いつ・つ",
        example: "五日 (いつか)",
        english: "Five days",
        nepali: "पाँच दिन",
      },
      {
        kanji: "六",
        onyomi: "ロク",
        kunyomi: "むっ・つ",
        example: "六時 (ろくじ)",
        english: "Six o'clock",
        nepali: "छ बजे",
      },
      {
        kanji: "七",
        onyomi: "シチ",
        kunyomi: "なな、なな・つ",
        example: "七日 (なのか)",
        english: "Seven days",
        nepali: "सात दिन",
      },
      {
        kanji: "八",
        onyomi: "ハチ",
        kunyomi: "やっ・つ",
        example: "八時 (はちじ)",
        english: "Eight o'clock",
        nepali: "आठ बजे",
      },
      {
        kanji: "九",
        onyomi: "キュウ、ク",
        kunyomi: "ここの・つ",
        example: "九日 (ここのか)",
        english: "Nine days",
        nepali: "नौ दिन",
      },
      {
        kanji: "十",
        onyomi: "ジュウ",
        kunyomi: "とお",
        example: "十日 (とおか)",
        english: "Ten days",
        nepali: "दस दिन",
      },
      {
        kanji: "百",
        onyomi: "ヒャク",
        kunyomi: "もも",
        example: "百円 (ひゃくえん)",
        english: "One hundred yen",
        nepali: "एक सय येन",
      },
      {
        kanji: "千",
        onyomi: "セン",
        kunyomi: "ち",
        example: "千円 (せんえん)",
        english: "One thousand yen",
        nepali: "एक हजार येन",
      },
      {
        kanji: "上",
        onyomi: "ジョウ",
        kunyomi: "うえ、あ・げる",
        example: "上手 (じょうず)",
        english: "Skilled",
        nepali: "निपुण",
      },
      {
        kanji: "下",
        onyomi: "カ、ゲ",
        kunyomi: "した、さ・げる",
        example: "下手 (へた)",
        english: "Unskilled",
        nepali: "अनिपुण",
      },
      {
        kanji: "左",
        onyomi: "サ",
        kunyomi: "ひだり",
        example: "左側 (ひだりがわ)",
        english: "Left side",
        nepali: "बाँया तर्फ",
      },
      {
        kanji: "右",
        onyomi: "ウ、ユウ",
        kunyomi: "みぎ",
        example: "右側 (みぎがわ)",
        english: "Right side",
        nepali: "दायाँ तर्फ",
      },
      {
        kanji: "中",
        onyomi: "チュウ",
        kunyomi: "なか",
        example: "中国 (ちゅうごく)",
        english: "China",
        nepali: "चीन",
      },
      {
        kanji: "大",
        onyomi: "ダイ、タイ",
        kunyomi: "おお・きい",
        example: "大学 (だいがく)",
        english: "University",
        nepali: "विश्वविद्यालय",
      },
      {
        kanji: "小",
        onyomi: "ショウ",
        kunyomi: "ちい・さい",
        example: "小さい (ちいさい)",
        english: "Small",
        nepali: "सानो",
      },
      {
        kanji: "月",
        onyomi: "ゲツ、ガツ",
        kunyomi: "つき",
        example: "月曜日 (げつようび)",
        english: "Monday",
        nepali: "सोमबार",
      },
      {
        kanji: "日",
        onyomi: "ニチ、ジツ",
        kunyomi: "ひ、か",
        example: "日曜日 (にちようび)",
        english: "Sunday",
        nepali: "आइतबार",
      },
      {
        kanji: "年",
        onyomi: "ネン",
        kunyomi: "とし",
        example: "今年 (ことし)",
        english: "This year",
        nepali: "यस बर्ष",
      },
      {
        kanji: "早",
        onyomi: "ソウ",
        kunyomi: "はや・い",
        example: "早い (はやい)",
        english: "Early/Fast",
        nepali: "चाँडो/द्रुत",
      },
      {
        kanji: "木",
        onyomi: "モク、ボク",
        kunyomi: "き",
        example: "木曜日 (もくようび)",
        english: "Thursday",
        nepali: "बिहिबार",
      },
      {
        kanji: "林",
        onyomi: "リン",
        kunyomi: "はやし",
        example: "林 (はやし)",
        english: "Grove",
        nepali: "जंगल",
      },
      {
        kanji: "山",
        onyomi: "サン",
        kunyomi: "やま",
        example: "山 (やま)",
        english: "Mountain",
        nepali: "पहाड",
      },
      {
        kanji: "川",
        onyomi: "セン",
        kunyomi: "かわ",
        example: "川 (かわ)",
        english: "River",
        nepali: "नदी",
      },
      {
        kanji: "土",
        onyomi: "ド、ト",
        kunyomi: "つち",
        example: "土曜日 (どようび)",
        english: "Saturday",
        nepali: "शनिबार",
      },
      {
        kanji: "空",
        onyomi: "クウ",
        kunyomi: "そら、あ・ける",
        example: "空 (そら)",
        english: "Sky",
        nepali: "आकाश",
      },
      {
        kanji: "田",
        onyomi: "デン",
        kunyomi: "た",
        example: "田んぼ (たんぼ)",
        english: "Rice field",
        nepali: "धान खेत",
      },
      {
        kanji: "天",
        onyomi: "テン",
        kunyomi: "あま",
        example: "天気 (てんき)",
        english: "Weather",
        nepali: "मौसम",
      },
      {
        kanji: "生",
        onyomi: "セイ、ショウ",
        kunyomi: "い・きる、う・まれる",
        example: "学生 (がくせい)",
        english: "Student",
        nepali: "विद्यार्थी",
      },
      {
        kanji: "花",
        onyomi: "カ",
        kunyomi: "はな",
        example: "花火 (はなび)",
        english: "Fireworks",
        nepali: "आतिशबाजी",
      },
      {
        kanji: "草",
        onyomi: "ソウ",
        kunyomi: "くさ",
        example: "草 (くさ)",
        english: "Grass",
        nepali: "घाँस",
      },
      {
        kanji: "虫",
        onyomi: "チュウ",
        kunyomi: "むし",
        example: "虫 (むし)",
        english: "Insect",
        nepali: "कीरा",
      },
      {
        kanji: "犬",
        onyomi: "ケン",
        kunyomi: "いぬ",
        example: "犬 (いぬ)",
        english: "Dog",
        nepali: "कुकुर",
      },
      {
        kanji: "人",
        onyomi: "ジン、ニン",
        kunyomi: "ひと",
        example: "日本人 (にほんじん)",
        english: "Japanese person",
        nepali: "जापानी व्यक्ति",
      },
      {
        kanji: "名",
        onyomi: "メイ、ミョウ",
        kunyomi: "な",
        example: "名前 (なまえ)",
        english: "Name",
        nepali: "नाम",
      },
      {
        kanji: "女",
        onyomi: "ジョ、ニョ",
        kunyomi: "おんな",
        example: "女の子 (おんなのこ)",
        english: "Girl",
        nepali: "केटी",
      },
      {
        kanji: "男",
        onyomi: "ダン、ナン",
        kunyomi: "おとこ",
        example: "男の子 (おとこのこ)",
        english: "Boy",
        nepali: "केटा",
      },
      {
        kanji: "子",
        onyomi: "シ、ス",
        kunyomi: "こ",
        example: "子供 (こども)",
        english: "Child",
        nepali: "बच्चा",
      },
      {
        kanji: "目",
        onyomi: "モク",
        kunyomi: "め",
        example: "目 (め)",
        english: "Eye",
        nepali: "आँखा",
      },
      {
        kanji: "耳",
        onyomi: "ジ",
        kunyomi: "みみ",
        example: "耳 (みみ)",
        english: "Ear",
        nepali: "कान",
      },
      {
        kanji: "口",
        onyomi: "コウ、ク",
        kunyomi: "くち",
        example: "口 (くち)",
        english: "Mouth",
        nepali: "मुख",
      },
      {
        kanji: "手",
        onyomi: "シュ",
        kunyomi: "て",
        example: "手紙 (てがみ)",
        english: "Letter",
        nepali: "चिठी",
      },
      {
        kanji: "足",
        onyomi: "ソク",
        kunyomi: "あし",
        example: "足 (あし)",
        english: "Foot",
        nepali: "खुट्टा",
      },
      {
        kanji: "見",
        onyomi: "ケン",
        kunyomi: "み・る",
        example: "見る (みる)",
        english: "To see",
        nepali: "हेर्नु",
      },
      {
        kanji: "音",
        onyomi: "オン",
        kunyomi: "おと",
        example: "音楽 (おんがく)",
        english: "Music",
        nepali: "संगीत",
      },
      {
        kanji: "力",
        onyomi: "リョク、リキ",
        kunyomi: "ちから",
        example: "力 (ちから)",
        english: "Power",
        nepali: "शक्ति",
      },
      {
        kanji: "気",
        onyomi: "キ、ケ",
        kunyomi: "き",
        example: "元気 (げんき)",
        english: "Energy/Health",
        nepali: "शक्ति/स्वास्थ्य",
      },
      {
        kanji: "円",
        onyomi: "エン",
        kunyomi: "まる・い",
        example: "円 (えん)",
        english: "Yen/Circle",
        nepali: "येन/गोलो",
      },
      {
        kanji: "入",
        onyomi: "ニュウ",
        kunyomi: "はい・る",
        example: "入る (はいる)",
        english: "To enter",
        nepali: "प्रवेश गर्नु",
      },
      {
        kanji: "出",
        onyomi: "シュツ",
        kunyomi: "で・る",
        example: "出る (でる)",
        english: "To exit",
        nepali: "निस्कनु",
      },
      {
        kanji: "立",
        onyomi: "リツ",
        kunyomi: "た・つ",
        example: "立つ (たつ)",
        english: "To stand",
        nepali: "उभिनु",
      },
      {
        kanji: "休",
        onyomi: "キュウ",
        kunyomi: "やす・む",
        example: "休む (やすむ)",
        english: "To rest",
        nepali: "आराम गर्नु",
      },
      {
        kanji: "先",
        onyomi: "セン",
        kunyomi: "さき",
        example: "先 (さき)",
        english: "Ahead",
        nepali: "अगाडि",
      },
      {
        kanji: "夕",
        onyomi: "セキ",
        kunyomi: "ゆう",
        example: "夕方 (ゆうがた)",
        english: "Evening",
        nepali: "साँझ",
      },
      {
        kanji: "本",
        onyomi: "ホン",
        kunyomi: "もと",
        example: "本 (ほん)",
        english: "Book",
        nepali: "पुस्तक",
      },
      {
        kanji: "文",
        onyomi: "ブン、モン",
        kunyomi: "ふみ",
        example: "作文 (さくぶん)",
        english: "Essay",
        nepali: "निबन्ध",
      },
      {
        kanji: "字",
        onyomi: "ジ",
        kunyomi: "あざ",
        example: "漢字 (かんじ)",
        english: "Kanji",
        nepali: "कांजी",
      },
      {
        kanji: "学",
        onyomi: "ガク",
        kunyomi: "まな・ぶ",
        example: "学校 (がっこう)",
        english: "School",
        nepali: "विद्यालय",
      },
      {
        kanji: "校",
        onyomi: "コウ",
        kunyomi: "こう",
        example: "学校 (がっこう)",
        english: "School",
        nepali: "विद्यालय",
      },
      {
        kanji: "村",
        onyomi: "ソン",
        kunyomi: "むら",
        example: "村 (むら)",
        english: "Village",
        nepali: "गाउँ",
      },
      {
        kanji: "町",
        onyomi: "チョウ",
        kunyomi: "まち",
        example: "町 (まち)",
        english: "Town",
        nepali: "शहर",
      },
      {
        kanji: "森",
        onyomi: "シン",
        kunyomi: "もり",
        example: "森 (もり)",
        english: "Forest",
        nepali: "जंगल",
      },
      {
        kanji: "正",
        onyomi: "セイ、ショウ",
        kunyomi: "ただ・しい",
        example: "正しい (ただしい)",
        english: "Correct",
        nepali: "सही",
      },
      {
        kanji: "水",
        onyomi: "スイ",
        kunyomi: "みず",
        example: "水 (みず)",
        english: "Water",
        nepali: "पानी",
      },
      {
        kanji: "火",
        onyomi: "カ",
        kunyomi: "ひ",
        example: "火曜日 (かようび)",
        english: "Tuesday",
        nepali: "मंगलबार",
      },
      {
        kanji: "玉",
        onyomi: "ギョク",
        kunyomi: "たま",
        example: "玉 (たま)",
        english: "Ball/Jewel",
        nepali: "बल/रत्न",
      },
      {
        kanji: "王",
        onyomi: "オウ",
        kunyomi: "おう",
        example: "王様 (おうさま)",
        english: "King",
        nepali: "राजा",
      },
      {
        kanji: "石",
        onyomi: "セキ",
        kunyomi: "いし",
        example: "石 (いし)",
        english: "Stone",
        nepali: "ढुङ्गा",
      },
      {
        kanji: "竹",
        onyomi: "チク",
        kunyomi: "たけ",
        example: "竹 (たけ)",
        english: "Bamboo",
        nepali: "बाँस",
      },
      {
        kanji: "貝",
        onyomi: "バイ",
        kunyomi: "かい",
        example: "貝 (かい)",
        english: "Shellfish",
        nepali: "सीप",
      },
      {
        kanji: "車",
        onyomi: "シャ",
        kunyomi: "くるま",
        example: "車 (くるま)",
        english: "Car",
        nepali: "कार",
      },
      {
        kanji: "金",
        onyomi: "キン、コン",
        kunyomi: "かね",
        example: "金曜日 (きんようび)",
        english: "Friday",
        nepali: "शुक्रबार",
      },
      {
        kanji: "雨",
        onyomi: "ウ",
        kunyomi: "あめ",
        example: "雨 (あめ)",
        english: "Rain",
        nepali: "वर्षा",
      },
      {
        kanji: "赤",
        onyomi: "セキ",
        kunyomi: "あか",
        example: "赤い (あかい)",
        english: "Red",
        nepali: "रातो",
      },
      {
        kanji: "青",
        onyomi: "セイ、ショウ",
        kunyomi: "あお",
        example: "青い (あおい)",
        english: "Blue",
        nepali: "निलो",
      },
      {
        kanji: "白",
        onyomi: "ハク、ビャク",
        kunyomi: "しろ",
        example: "白い (しろい)",
        english: "White",
        nepali: "सेतो",
      },
    // ...more Kanji data...
];

let currentIndex = 0;
let hardKanjiList = [];

const kanjiElement = document.getElementById("kanji");
const readingsElement = document.getElementById("readings");
const showReadingsButton = document.getElementById("show-readings");
const nextKanjiButton = document.getElementById("next-kanji");
const markHardButton = document.getElementById("mark-hard");
const hardKanjiListElement = document.getElementById("hard-kanji-list");
const exampleElement = document.getElementById("example");
const translationsElement = document.getElementById("translations");

function displayKanji() {
    const currentKanji = kanjiList[currentIndex];
    kanjiElement.textContent = currentKanji.kanji;
    readingsElement.textContent = "";
    exampleElement.textContent = "";
    translationsElement.textContent = "";
}

function showReadings() {
    const currentKanji = kanjiList[currentIndex];
    readingsElement.textContent = `Onyomi: ${currentKanji.onyomi}\n<br>Kunyomi: ${currentKanji.kunyomi}`;
    exampleElement.textContent = `Example: ${currentKanji.example}`;
    translationsElement.innerHTML = `English: ${currentKanji.english}<br>Nepali: ${currentKanji.nepali}`;
}

function nextKanji() {
    currentIndex = (currentIndex + 1) % kanjiList.length;
    displayKanji();
}

function markHard() {
    const currentKanji = kanjiList[currentIndex];
    if (!hardKanjiList.includes(currentKanji.kanji)) {
        hardKanjiList.push(currentKanji.kanji);
        updateHardKanjiList();
    }
}

function updateHardKanjiList() {
    hardKanjiListElement.innerHTML = hardKanjiList.map(kanji => `<li>${kanji}</li>`).join("");
}

// Event Listeners
showReadingsButton.addEventListener("click", showReadings);
nextKanjiButton.addEventListener("click", nextKanji);
markHardButton.addEventListener("click", markHard);

// Initial Display
displayKanji();
